name: PHP Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check PHP syntax errors
      uses: overtrue/phplint@3.0.3
      with:
        path: .
        options: --exclude=*.log
